=== Dragonlaird/RemoteCockpit/InstrumentPlugins/GenericInstruments/InstrumentDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
  elementFormDefault="qualified"
  vc:minVersion="1.1">

  <!--Instrument Root Element-->
  <xsd:element name="InstrumentDefinition">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Name" type="xsd:string" />
        <xsd:element name="Type" type="xsd:unsignedByte" />
        <xsd:element name="Author" type="xsd:string" />
        <xsd:element name="CreateDate" type="xsd:string" />
        <xsd:element name="Aircraft" type="xsd:string" />
        <xsd:element name="AnimationUpdateInMs" type="xsd:unsignedByte" />
        <xsd:element name="BackgroundImagePath" type="xsd:string"/>
        <xsd:element name="Animations" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Animation" type="AnimationImage" maxOccurs="unbounded">
                <xsd:alternative test="@type = 1" type="AnimationDrawing"/>
                <xsd:alternative test="@type = 2" type="AnimationExternal"/>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!--Animation Elements-->
  <!--Animation Image-->
  <xsd:complexType name="AnimationImage">
    <xsd:sequence>
        <xsd:element name="Name" type="xsd:string" />
        <xsd:element name="LastAppliedValue" type="xsd:float" />
        <xsd:element name="Triggers" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Trigger" type="TriggerTimer" maxOccurs="unbounded">
                <xsd:alternative test="@type = 1" type="TriggerClientRequest"/>
                <xsd:alternative test="@type = 2" type="TriggerMouseClick"/>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Animation Drawing-->
  <xsd:complexType name="AnimationDrawing">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="Type" type="xsd:unsignedByte" />
      <xsd:element name="LastAppliedValue" type="xsd:float" />
      <xsd:element name="FillMethod" type="xs.unsignedByte" />
      <xsd:element name="Triggers" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Trigger" type="TriggerTimer" maxOccurs="unbounded">
              <xsd:alternative test="@type = 1" type="TriggerClientRequest"/>
              <xsd:alternative test="@type = 2" type="TriggerMouseClick"/>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Animation External-->
  <xsd:complexType name="AnimationExternal">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="Type" type="xsd:unsignedByte" />
      <xsd:element name="LastAppliedValue" type="xsd:float" />
      <xsd:element name="Triggers" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Trigger" type="TriggerTimer" maxOccurs="unbounded">
              <xsd:alternative test="@type = 1" type="TriggerClientRequest"/>
              <xsd:alternative test="@type = 2" type="TriggerMouseClick"/>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Trigger Elements-->
  <!--Trigger Mouse Click-->
  <xsd:complexType name="TriggerTimer">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="ElapsedTimeInMs" type="xsd:unsignedInt"/>
      <xsd:element name="Actions" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Action" type="ActionRotate" maxOccurs="unbounded">
              <xsd:alternative test="@type = 1" type="ActionMove"/>
              <xsd:alternative test="@type = 2" type="ActionMove"/>
              <xsd:alternative test="@type = 3" type="ActionClip"/>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Trigger Client Request-->
  <xsd:complexType name="TriggerClientRequest">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="Request" type="ClientRequest" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="Actions" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Action" type="ActionRotate" maxOccurs="unbounded">
              <xsd:alternative test="@type = 1" type="ActionMove"/>
              <xsd:alternative test="@type = 2" type="ActionMove"/>
              <xsd:alternative test="@type = 3" type="ActionClip"/>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Trigger Mouse Click-->
  <xsd:complexType name="TriggerMouseClick">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="ClickZone" type="Rectangle"/>
      <xsd:element name="Actions" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Action" type="ActionRotate" maxOccurs="unbounded">
              <xsd:alternative test="@type = 1" type="ActionMove"/>
              <xsd:alternative test="@type = 2" type="ActionMove"/>
              <xsd:alternative test="@type = 3" type="ActionClip"/>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Action Components-->
  <!--Action Clip-->
  <xsd:complexType name="ActionClip">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Type" type="xsd:unsignedByte" />
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Action Move-->
  <xsd:complexType name="ActionMove">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Type" type="xsd:unsignedByte" />
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Action Rotate-->
  <xsd:complexType name="ActionRotate">
    <xsd:sequence maxOccurs="unbounded">
      <xsd:element name="Type" type="xsd:unsignedByte" />
      <xsd:element name="CentrePoint">
        <xsd:complexType>
          <xsd:sequence maxOccurs="1">
            <xsd:element name="X" type="xsd:float" />
            <xsd:element name="Y" type="xsd:float" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="RotateClockwise" type="xsd:boolean"/>
      <xsd:element name="MaximumValueExpected" type="xsd:float"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="xsd:unsignedByte"/>
  </xsd:complexType>

  <!--Client Request Element-->
  <xsd:complexType name="ClientRequest">
    <xsd:sequence minOccurs="1" maxOccurs="1">
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="Unit" type="xsd:string" />
    </xsd:sequence>
  </xsd:complexType>

  <!--Rectangle Element-->
  <xsd:complexType name="Rectangle">
    <xsd:sequence minOccurs="1" maxOccurs="1">
      <xsd:element name="Top" type="xsd:float" />
      <xsd:element name="Left" type="xsd:float" />
      <xsd:element name="Height" type="xsd:float"/>
      <xsd:element name="Width" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>

  <!--Types-->
  <xsd:complexType name="animationtype">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="Type" type="xsd:unsignedInt" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>


  <xsd:complexType name="triggertype">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="Type" type="xsd:unsignedInt" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="actiontype">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="Type" type="xsd:unsignedInt" use="required" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

</xsd:schema>

=== Dragonlaird/RemoteCockpit/InstrumentPlugins/GenericInstruments/Generic_Bearing_Indicator.xml
<InstrumentDefinition
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
  xsi:noNamespaceSchemaLocation="InstrumentDefinition.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  vc:minVersion="1.1">
  <Name>Generic Bearing Indicator</Name>
  <Type>3</Type>
  <Author>Dragonlaird</Author>
  <CreateDate>2021-01-27T06:45:00</CreateDate>
  <Aircraft>Generic</Aircraft>
  <AnimationUpdateInMs>50</AnimationUpdateInMs>
  <BackgroundImagePath>.\InstrumentImages\Bearing_Background.png</BackgroundImagePath>
  <Animations>
    <Animation type="0">
      <Name>Bearing</Name>
      <ImagePath>.\InstrumentImages\Bearing_Foreground.png</ImagePath>
      <Triggers>
        <Trigger type="1">
          <Name>Guage</Name>
          <Request>
            <Name>MAGNETIC COMPASS</Name>
            <Unit>degrees</Unit>
          </Request>
          <Actions>
            <Action type="0">
              <CentrePoint>
                <X>-50.0</X>
                <Y>50.0</Y>
              </CentrePoint>
              <RotateClockwise>false</RotateClockwise>
              <MaximumValueExpected>360.0</MaximumValueExpected>
              <MinimumValueExpected>0.0</MinimumValueExpected>
            </Action>
          </Actions>
        </Trigger>
      </Triggers>
    </Animation>
  </Animations>
</InstrumentDefinition>
